### ISSUE TITLE
Negative logprob in "(2 ** (logprobs - logn)).cumsum()"?

### ISSUE THREAD

**Issue by rafaveguim** [matteodellamico/montecarlopwd#1]
Line 40 in model.py:
`(2 ** (logprobs - logn)).cumsum()`

`(2 ** (logprobs - logn))` translates into `prob * (1/n)`, but Dell'Amico and Filippone (2015) Section 3.2 suggests `1/(prob * n)`. Is line 40 correct or it should be `(2 ** (- logprobs - logn))`?

Cheers

**Comment by matteodellamico** [comment]
With some abuse of notation, logprobs are changed of sign (see e.g. how they're generated in pcfg.py, backoff.py or ngram_chain.py).

Thanks for the comment, I've updated model.Model with some docstring to clarify that. If you continue going through the code, please let me know anything that would benefit from being better documented.
